all:
  children:
    esxi_hosts:
      hosts:
        esxi-prod-01:
          ansible_host: 192.168.1.200 
        esxi-replica-01:
          ansible_host: 192.168.1.201  
      vars:
        ansible_user: "root"
        ansible_ssh_pass: "z3Zv#H5$-7J2!zg@zC4B" 

    vcenter:
      hosts:
        vcenter-lab:
          ansible_host: 192.168.1.199
      vars:
        ansible_user: "administrator@vsphere.local"
        ansible_password: "-$Mc!CU9Dr6#s89b"
